<a href="https://colab.research.google.com/github/ashishbhatta/Day_Ahead_Market_Simulation_in_Assume/blob/main/demand_df_extractor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data from January 1 2026 to January 31 2026 is used for creating a demad file for simulation.

The data is extrated using the script https://github.com/ashishbhatta/Day_Ahead_Market_Simulation_in_Assume/tree/main/IEX_scraping

The data is stored in https://github.com/ashishbhatta/Day_Ahead_Market_Simulation_in_Assume/blob/main/IEX_Aggrigated_suply_demand.csv

In [170]:
import pandas as pd
import numpy as np

In [171]:

df = pd.read_csv("https://raw.githubusercontent.com/ashishbhatta/Day_Ahead_Market_Simulation_in_Assume/refs/heads/main/IEX_Aggrigated_suply_demand.csv")
df.tail()

,Date,Source URL,Time Block,Price (in Rs./MWh),Buy / Demand (in MW),Sell / Supply (in MW)
29755,31-01-2026,https://www.iexindia.com/market-data/day-ahead...,23:45-24:00,5001-6000,2120.4,25100.3
29756,31-01-2026,https://www.iexindia.com/market-data/day-ahead...,23:45-24:00,6001-7000,2120.2,25112.8
29757,31-01-2026,https://www.iexindia.com/market-data/day-ahead...,23:45-24:00,7001-8000,2120.2,25122.8
29758,31-01-2026,https://www.iexindia.com/market-data/day-ahead...,23:45-24:00,8001-9000,2120.2,25160.4
29759,31-01-2026,https://www.iexindia.com/market-data/day-ahead...,23:45-24:00,9001-10000,2120.2,25255.0

In [172]:
df.head()

,Date,Source URL,Time Block,Price (in Rs./MWh),Buy / Demand (in MW),Sell / Supply (in MW)
0,1/1/2026,https://www.iexindia.com/market-data/day-ahead...,00:00-00:15,0-1000,8159.3,2147.7
1,1/1/2026,https://www.iexindia.com/market-data/day-ahead...,00:00-00:15,1001-2000,7110.1,2982.9
2,1/1/2026,https://www.iexindia.com/market-data/day-ahead...,00:00-00:15,2001-3000,5920.8,5264.5
3,1/1/2026,https://www.iexindia.com/market-data/day-ahead...,00:00-00:15,3001-4000,4339.3,15535.3
4,1/1/2026,https://www.iexindia.com/market-data/day-ahead...,00:00-00:15,4001-5000,1881.8,20416.7

In [173]:
# In the Date column some date are in format d/m/y while others are in d-m-y so converting them to the same format.

df['Date'] = df['Date'].str.replace('-', '/')

In [174]:
# Creating a new column "datetime" containg the date and time information.

df[['Start_Time', 'End_Time']] = df['Time Block'].str.split('-', expand=True)
df['datetime'] = pd.to_datetime(
    df['Date'] + ' ' + df['Start_Time'], format='%d/%m/%Y %H:%M'
)
df.drop(['Source URL','Time Block','Date'],axis=1,inplace=True)
col = df.pop('datetime')
df.insert(0, 'datetime', col)
df.tail()

,datetime,Price (in Rs./MWh),Buy / Demand (in MW),Sell / Supply (in MW),Start_Time,End_Time
29755,2026-01-31 23:45:00,5001-6000,2120.4,25100.3,23:45,24:00
29756,2026-01-31 23:45:00,6001-7000,2120.2,25112.8,23:45,24:00
29757,2026-01-31 23:45:00,7001-8000,2120.2,25122.8,23:45,24:00
29758,2026-01-31 23:45:00,8001-9000,2120.2,25160.4,23:45,24:00
29759,2026-01-31 23:45:00,9001-10000,2120.2,25255.0,23:45,24:00

In [175]:
df.tail()

,datetime,Price (in Rs./MWh),Buy / Demand (in MW),Sell / Supply (in MW),Start_Time,End_Time
29755,2026-01-31 23:45:00,5001-6000,2120.4,25100.3,23:45,24:00
29756,2026-01-31 23:45:00,6001-7000,2120.2,25112.8,23:45,24:00
29757,2026-01-31 23:45:00,7001-8000,2120.2,25122.8,23:45,24:00
29758,2026-01-31 23:45:00,8001-9000,2120.2,25160.4,23:45,24:00
29759,2026-01-31 23:45:00,9001-10000,2120.2,25255.0,23:45,24:00

In [176]:
df2 = df.pivot_table(index = "datetime", columns = "Price (in Rs./MWh)",values="Buy / Demand (in MW)")
df2.columns.name = None # used to remove multi index column

In [177]:
df2.tail()

,0-1000,1001-2000,2001-3000,3001-4000,4001-5000,5001-6000,6001-7000,7001-8000,8001-9000,9001-10000
datetime,,,,,,,,,,
2026-01-31 22:45:00,9910.8,8870.80,7326.8,5393.4,2985.8,2151.1,2068.5,2068.5,2068.5,2068.5
2026-01-31 23:00:00,9687.9,8648.47,7100.2,5236.6,2968.8,2344.1,2343.9,2343.9,2343.9,2343.9
2026-01-31 23:15:00,9397.7,8357.70,6809.0,5014.2,2862.2,2312.1,2311.9,2311.9,2311.9,2311.9
2026-01-31 23:30:00,9229.2,8189.20,6642.5,4857.7,2687.7,2229.0,2228.8,2228.8,2228.8,2228.8
2026-01-31 23:45:00,8964.9,7925.90,6376.2,4591.3,2518.1,2120.4,2120.2,2120.2,2120.2,2120.2

In [178]:
# Subtracting the demand from adjascent demand coulumn

# 1. Identify price columns in order (excluding datetime)
price_columns = [col for col in df2.columns if col.lower() != 'datetime']

# 2. Subtract adjacent columns horizontally
for i in range(len(price_columns)):
    col1 = price_columns[i]

    if i < len(price_columns) - 1:
        col2 = price_columns[i + 1]
        # Column_i - Column_{i+1}
        df2[f'Demand_{i+1}'] = (df2[col1] - df2[col2]).abs().round(2)
    else:
        # Last column: Column_10 - 0 (value remains unchanged)
        df2[f'Demand_{i+1}'] = df2[col1].abs().round(2)

df2.drop(columns=df2.columns[:10], inplace=True)
df2.head()

,Demand_1,Demand_2,Demand_3,Demand_4,Demand_5,Demand_6,Demand_7,Demand_8,Demand_9,Demand_10
datetime,,,,,,,,,,
2026-01-01 00:00:00,1049.2,1189.3,1581.5,2457.5,191.5,0.0,0.0,6.58,16.32,1667.4
2026-01-01 00:15:00,1049.2,1192.3,1895.5,2359.1,153.8,0.0,0.0,5.43,13.47,1686.3
2026-01-01 00:30:00,1049.2,1192.3,2102.5,2911.4,132.1,0.0,0.0,4.00,9.90,1705.4
2026-01-01 00:45:00,1048.2,1193.3,2214.5,3332.4,111.2,0.0,0.0,2.27,5.63,1716.4
2026-01-01 01:00:00,1049.2,1203.3,3448.3,2365.0,110.3,0.0,0.0,1.41,3.49,1635.5

In [179]:
df2.tail()

,Demand_1,Demand_2,Demand_3,Demand_4,Demand_5,Demand_6,Demand_7,Demand_8,Demand_9,Demand_10
datetime,,,,,,,,,,
2026-01-31 22:45:00,1040.00,1544.00,1933.4,2407.6,834.7,82.6,0.0,0.0,0.0,2068.5
2026-01-31 23:00:00,1039.43,1548.27,1863.6,2267.8,624.7,0.2,0.0,0.0,0.0,2343.9
2026-01-31 23:15:00,1040.00,1548.70,1794.8,2152.0,550.1,0.2,0.0,0.0,0.0,2311.9
2026-01-31 23:30:00,1040.00,1546.70,1784.8,2170.0,458.7,0.2,0.0,0.0,0.0,2228.8
2026-01-31 23:45:00,1039.00,1549.70,1784.9,2073.2,397.7,0.2,0.0,0.0,0.0,2120.2

In [180]:
df2.to_csv('demand_df.csv')